### ISSUE TITLE
Make stream scanning chunk size parametrizable

### ISSUE THREAD

**Issue by igorlovich** [cdarras/clamav-client#28]
Currently the chunk size is fixed at 2048 bytes. For scanning large files this creates quite a bit of overhead (on our infrastructure e.g. a 70Mb file takes ~50 sec to scan with the default chunk size, where as with a 1Mb chunk size it takes about 15 sec.) Would a PR that makes this value parametrizable (with default left as is at 2048) be accepted ?

**Comment by cdarras** [comment]
Yes, sure!

**Comment by igorlovich** [comment]
@cdarras when do you think you'll be able to take a look at the PR ?

**Comment by igorlovich** [comment]
thanks. @cdarras  are you going to publish a release to maven ?
