### ISSUE TITLE
Compress file scan seems not working

### ISSUE THREAD

**Issue by gssitrainee** [cdarras/clamav-client#4]
The test viruses I downloaded from eicar site was compressed into a single zip file. My realtime protection (Antivirus was turned off all throughout). I tried scanning the compressed file but is seems it is returning OK result. Not sure though if I try a real virus compressed file. Btw, my clamd is updated.

Not sure if there is something I need to do in the code for it to scan the compressed files.

Thanks

**Comment by cdarras** [comment]
Hello,
The archive scanning feature is enabled by a server-side setting. Could you please check that `ScanArchive 1` is set in your `clamd.conf` file?
